CREATE TABLE IF NOT EXISTS webinars (
    record_id VARCHAR(255) PRIMARY KEY,
    name VARCHAR(255),
    contact_record_id VARCHAR(255), -- Foreign key to contacts table
    phone VARCHAR(255),
    instagram VARCHAR(255),
    manager_responsible VARCHAR(255),
    stage VARCHAR(255),
    sales_department VARCHAR(255),
    leader_of_sales_department VARCHAR(255),
    webinar_date DATE,
    left_request BOOLEAN,
    watched_webinar BOOLEAN,
    created_how VARCHAR(255),
    source VARCHAR(255),
    email VARCHAR(255),
    number_of_emails INT,
    number_of_phone_calls INT,
    number_of_calendar_events INT,
    number_of_files INT,
    created_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE,
    last_interaction_date TIMESTAMP WITH TIME ZONE,
    days_on_stage INT,
    utm_source VARCHAR(255),
    utm_medium VARCHAR(255),
    utm_campaign VARCHAR(255),
    utm_term VARCHAR(255),
    utm_content VARCHAR(255),
    utm_id VARCHAR(255)
); 